_target_: models.unet.UNetModel

model_channels: 128
num_res_blocks: 2
channel_mult: [1, 2, 2, 2]
attention_resolutions: [16, 8]
dropout: 0.1
use_scale_shift_norm: true
image_size: ${dataset.image_size}
in_channels: ${dataset.channels}
out_channels: ${dataset.channels}
bidirectional: ${mode.bidirectional}
